In [2]:
import numpy as np
import math as math
import matplotlib.pylab as plt
from mpl_toolkits.mplot3d import Axes3D
from numpy import sin,cos,pi,exp,sqrt
from mpl_toolkits.mplot3d.art3d import Poly3DCollection, Line3DCollection

from ipywidgets import interact, interactive, fixed, interact_manual, FloatSlider
import ipywidgets as widgets
from IPython.display import display, Latex, Markdown

#this is the library that contains all the rigid body tranforms functions
import transforms
import allfunc as fn

In [9]:


R = np.array([[0.28429800, -0.73343736, 0.61744983], [0.06259641, -0.62845074, -0.77532661], [0.95669030, 0.25907395, -0.13275674]])

w = fn.so3ToVec(fn.MatrixLog3(R))

norm = np.sqrt((1.84204091)**2+(-0.604113)**2+(1.41756185)**2)
wn = w/norm
print(wn)


[ 0.7670146  -0.25154897  0.59026411]


In [10]:
w = [-0.67999765, 0.61368655, 0.42461134]

print(np.array_repr(fn.VecToso3(w)))




array([[ 0.        , -0.42461134,  0.61368655],
       [ 0.42461134,  0.        ,  0.67999765],
       [-0.61368655, -0.67999765,  0.        ]])


In [ ]:
import numpy as np

T_sb = np.array([[-0.49149800, -0.39128840, 0.77802513, -0.00791424], [-0.57514800, 0.81667549, 0.04739121, 0.60341557], [-0.65393768, -0.42418691, -0.62644311, -0.78039705], [0.00000000, 0.00000000, 0.00000000, 1.00000000]])
V_sb_in_s = np.array([[-0.84892393], [0.30351397], [-0.62740668], [-0.06780123], [0.45784045], [1.11356592]])
q_B = np.array([[-0.36707501], [1.72487417], [1.68678776], [1.00000000]])

V_b = se3ToVec(np.linalg.inv(T_sb)@(VecTose3(V_sb_in_s))@T_sb)

x_w = V_b[0][0]
y_w = V_b[1][0]
z_w = V_b[2][0]

w = np.array([x_w, y_w, z_w])

x_v = V_b[3][0]
y_v = V_b[4][0]
z_v = V_b[5][0]

v = np.array([x_v, y_v, z_v])

# print(transforms.to_skew(w))

# printM = (se3ToVec(MatrixLog6(T_1in0)))
printM = MatrixExp3(VecToso3(w))@q_B[:3]



printM = (np.linalg.inv(T_sb)@(VecTose3(V_sb_in_s))@T_sb)@q_B


print("[", end ="")

for row in (printM):
    print(end =" ")
    for col in row[:len(row)-1]:
        print(col, end =", ")
    print(row[len(row)-1],", ")
#     print(row,"], ")
print("]")

In [11]:
def twistToMatrix(V):
    omega = np.array([V[i] for i in range(3)])
    vel = np.array([V[i] for i in range(3,6)])
    w01 = omega
    t = 1
    w01_matrix = formSkewSymm(w01)
    T = np.c_[w01_matrix, vel]
    T = np.r_[T,[[0,0,0,0]] ]
    return T
T_sb = np.array([[0.67371517, 0.70932345, 0.20728751, -0.27189915], 
                 [-0.66726116, 0.70445204, -0.24188812, -0.82453819], 
                 [-0.31760102, 0.02464879, 0.94790402, -0.72079041], 
                 [0.00000000, 0.00000000, 0.00000000, 1.00000000]])

V_sb_in_s = np.array([[-0.00902475], [0.07488817], [-0.51614565], [0.37954615], [-0.37525155], [0.27769225]])
q_B = np.array([[-1.04786443], [-1.56375671], [0.30064309], [1.00000000]])
T_bs = np.linalg.inv(T_sb)
Ad = makeAdj(T_bs)
V_b = np.matmul(Ad, V_sb_in_s)
T = twistToMatrix(V_b)
print(T)
print(np.array_repr(np.matmul(T, q_B) ))



NameError: name 'makeAdj' is not defined

In [24]:
import numpy as np

T_02 = np.array([[-0.52336615, -0.17949695, 0.83298783, -0.48688017], [0.47535490, 0.74981175, 0.46023912, 0.22033626], [-0.70719558, 0.63683842, -0.30710134, -0.20697747], [0.00000000, 0.00000000, 0.00000000, 1.00000000]])
v_2 = np.array([[0.54884595], [-0.05387133], [0.88709294],[0]])

V_0 = fn.Adjoint(T_02)@v_2


print(np.array_repr()


ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 3 is different from 6)

In [23]:
import numpy as np

p_8in2 = np.array([[-0.31543701], [-0.67358802], [-0.05370352]])
R_8in2 = np.array([[0.02445569, -0.72935367, -0.68369960], [0.44954349, -0.60283361, 0.65916787], [-0.89292361, -0.32347311, 0.31313348]])


print(np.array_repr(-(np.linalg.inv(R_8in2))@p_8in2))


array([[ 0.2625682 ],
       [-0.65349829],
       [ 0.2451598 ]])


In [20]:


import numpy as np

T_1in6 = np.array([[0.37786601, -0.84547299, 0.37734958, -0.20259576], [0.65301483, -0.04555357, -0.75597387, -0.35260906], [0.65634511, 0.53207171, 0.53489326, 0.59195523], [0.00000000, 0.00000000, 0.00000000, 1.00000000]])
T_2in1 = np.array([[0.50520491, -0.34911735, -0.78923068, 0.30575427], [-0.85084642, -0.04856099, -0.52316555, 0.33583556], [0.14432034, 0.93581991, -0.32157850, 0.90981626], [0.00000000, 0.00000000, 0.00000000, 1.00000000]])


print((T_1in6)@(T_2in1))



[[ 7.96326711e-04,  0.00000000e+00,  9.99999683e-01,
         0.00000000e+00],
       [ 0.00000000e+00,  1.00000000e+00,  0.00000000e+00,
         0.00000000e+00],
       [-9.99999683e-01,  0.00000000e+00,  7.96326711e-04,
         0.00000000e+00],
       [ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
         1.00000000e+00]]





[[ 0.96472665  0.26226868  0.02275138 -0.02768273]
 [ 0.25956298 -0.93322208 -0.24844234 -0.85604282]
 [-0.04392656  0.24558437 -0.96837946  1.45797874]
 [ 0.          0.          0.          1.        ]]
