In [1]:
import numpy as np
import math as math
import matplotlib.pylab as plt
from mpl_toolkits.mplot3d import Axes3D
from numpy import sin,cos,pi,exp,sqrt
from mpl_toolkits.mplot3d.art3d import Poly3DCollection, Line3DCollection

from ipywidgets import interact, interactive, fixed, interact_manual, FloatSlider
import ipywidgets as widgets
from IPython.display import display, Latex, Markdown

#this is the library that contains all the rigid body tranforms functions
import transforms as tm
import robot_kinematics as rk
import allfunc as fn

In [2]:
# q1

t0a = rk.translate([0., 2., 2.])
tab = tm.hom(tm.Rx(np.pi/2+0.73) , [0., 0., 0.])
# tbc = rk.translate([0., 0., -.45])
tb1 = rk.translate([0., 2., 0.])

t01 = t0a@tab@tb1

print(np.array_repr(t01))

array([[ 1.        ,  0.        ,  0.        ,  0.        ],
       [ 0.        , -0.66686964, -0.7451744 ,  0.66626073],
       [ 0.        ,  0.7451744 , -0.66686964,  3.4903488 ],
       [ 0.        ,  0.        ,  0.        ,  1.        ]])


In [3]:
# q2

theta = np.array([[0.18, 0.06, 0.50]])

t0a = rk.translate([0., -2., 0.])
tab = tm.hom(tm.Rx(-0.36) , [0., 0., 0.])

tbc = rk.translate([0., 0., 2.])
tcd = tm.hom(tm.Rx(-0.7), [0., 0., 0.])

tde = rk.translate([0., -2., 2.])
tef = tm.hom(tm.Rz(-0.37+np.pi), [0., 0., 0.])

tf1 = rk.translate([0., 0., 2.])


t01 = t0a@tab@tbc@tcd@tde@tef@tf1

print(np.array_repr(t01))

array([[-0.93232735, -0.36161543,  0.        ,  0.        ],
       [ 0.17678369, -0.45578881,  0.87235548,  1.21622623],
       [-0.3154572 ,  0.81332087,  0.48887208,  5.57199294],
       [ 0.        ,  0.        ,  0.        ,  1.        ]])


In [4]:
# q3

j = np.array([[0], [0], [0], [0], [1], [0]])

print(np.array_repr(j))

array([[0],
       [0],
       [0],
       [0],
       [1],
       [0]])


In [5]:
# q4

j = np.array([[0], [0], [0], [0], [1], [0]])
dtheta = np.array([-0.1])

print(np.array_repr(j*dtheta))

array([[-0. ],
       [-0. ],
       [-0. ],
       [-0. ],
       [-0.1],
       [-0. ]])


In [24]:
# q5

import numpy as np

theta = np.array([[-0.40000000], [-0.72000000], [-0.53000000], [-0.14000000], [0.23000000], [0.16000000], [0.10000000], [-0.04000000]])
dtheta = np.array([[-0.30000000], [0.99000000], [0.42000000], [-0.30000000], [0.44000000], [0.75000000], [-0.50000000], [-0.35000000]])
jacobian = np.array([[0.00000000, 0.00000000, 0.00000000, 0.00000000, 0.00000000, 1.00000000,  0.00000000, 0.99500417], [0.00000000, 0.00000000, 0.00000000, 0.00000000, 0.00000000, 0.00000000,  -0.98722728, -0.01590528], [0.00000000, 0.00000000, 0.00000000, 0.00000000, 0.00000000, 0.00000000,  -0.15931821, 0.09855827], [0.00000000, -1.00000000, 0.00000000, 1.00000000, 1.00000000, 0.00000000,  0.28084855, -0.58930916], [0.00000000, 0.00000000, 0.00000000, 0.00000000, 0.00000000, 0.93000000,  0.44768416, -0.93681766], [-1.00000000, 0.00000000, -1.00000000, 0.00000000, 0.00000000,  -4.00000000, -2.77410867, 5.79824209]])
T_1in0 = np.array([[0.09975356, 0.99500417, -0.00399227, 4.80000833], [0.11891692, -0.01590528, -0.99277681, -5.90408340], [-0.98788056, 0.09855827, -0.11990944, -0.46606552], [0.00000000, 0.00000000, 0.00000000, 1.00000000]])

print(np.array_repr(tm.adjoint(np.linalg.inv(T_1in0))@jacobian@dtheta))

array([[ 0.0548205 ],
       [ 0.39625312],
       [-0.50259425],
       [ 8.4955056 ],
       [-1.60633111],
       [-0.17099807]])
