In [1]:
import numpy as np
import math as math
import matplotlib.pylab as plt
from mpl_toolkits.mplot3d import Axes3D
from numpy import sin,cos,pi,exp,sqrt
from mpl_toolkits.mplot3d.art3d import Poly3DCollection, Line3DCollection

from ipywidgets import interact, interactive, fixed, interact_manual, FloatSlider
import ipywidgets as widgets
from IPython.display import display, Latex, Markdown

#this is the library that contains all the rigid body tranforms functions
import transforms as tm
import robot_kinematics as rk
import allfunc as fn

In [84]:
# q1 space

T = np.zeros([4,4])
T[3,3] = 1

# x y and z pos
T[0,3] = 2
T[1,3] = 0
T[2,3] = 0

# new x in s frame
T[0,0] = 0
T[1,0] = -1
T[2,0] = 0
# new y in s frame
T[0,1] = 0
T[1,1] = 0
T[2,1] = -1
# new z in s frame
T[0,2] = 1
T[1,2] = 0
T[2,2] = 0

theta = np.array([[-0.92000000], [0.38000000], [0.87000000]])

t0a = tm.hom(tm.Rx(-1*theta[0]), [0., 2., -2.])


tab = tm.hom(tm.Rz(-1*theta[1]), [0., -2., 0.])


tbc = tm.hom(tm.Ry(-1*theta[2]), [0., 0., -2.])


tc1 = tm.hom(tm.Rz(0), [0., 2., 0.])


t01 = t0a@tab@tbc@tc1

t10 = np.linalg.inv(t01)

j1 = np.array([[-1.], [0.], [0.], [0.], [0.], [0.]])

j2 = np.array([[0.], [0.], [-1.], [0.], [0.], [0.]])

j3 = np.array([[0.], [-1.], [0.], [0.], [0.], [0.]])


j = np.array([[0., 1., 1.], [0., 0., 0.], [1., 0., 0.], [0., 0., 0.], [1., 0., 0.], [0., 0., 0.]])

jspace1 = rk.getAdjoint(t0a)@j1

jspace2 = rk.getAdjoint(t0a@tab)@j2

jspace3 = rk.getAdjoint(t0a@tab@tbc)@j3

J = np.c_[jspace2, jspace3]
J = np.c_[jspace1, J]

print(np.array_repr(J))
# print(np.array_repr(jspace2))
# print(np.array_repr(jspace3))


array([[-1.        ,  0.        , -0.37092047],
       [ 0.        ,  0.79560162, -0.56260375],
       [ 0.        , -0.60582016, -0.73884709],
       [ 0.        ,  2.37956293, -4.46023096],
       [ 2.        ,  0.        ,  1.78147299],
       [ 2.        ,  0.        ,  0.8826286 ]])


In [37]:
# q1 body

T = np.zeros([4,4])
T[3,3] = 1

# x y and z pos
T[0,3] = 2
T[1,3] = 0
T[2,3] = 0

# new x in s frame
T[0,0] = 0
T[1,0] = -1
T[2,0] = 0
# new y in s frame
T[0,1] = 0
T[1,1] = 0
T[2,1] = -1
# new z in s frame
T[0,2] = 1
T[1,2] = 0
T[2,2] = 0

theta = np.array([[0.09000000], [0.29000000], [0.23000000]])

t0a = tm.hom(tm.Rx(theta[0]) , [0., -2., 0.])


tab = tm.hom(tm.Rx(theta[1]), [-2., -6., 0.])


tbc = rk.translate([0., -2., -1*theta[2]])


tc1 = tm.hom(tm.Rz(0), [0., 2., 0.])


t01 = t0a@tab@tbc@tc1

t10 = np.linalg.inv(t01)

j1 = np.array([[1.], [0.], [0.], [0.], [0.], [0.]])

j2 = np.array([[1.], [0.], [0.], [0.], [0.], [0.]])

j3 = np.array([[0.], [0.], [0.], [0.], [0.], [-1.]])


j = np.array([[0., 1., 1.], [0., 0., 0.], [1., 0., 0.], [0., 0., 0.], [1., 0., 0.], [0., 0., 0.]])

jspace1 = rk.getAdjoint(np.linalg.inv(tab@tbc@T))@j1

jspace2 = rk.getAdjoint(np.linalg.inv(tbc@T))@j2

jspace3 = rk.getAdjoint(np.linalg.inv(T))@j3

J = np.c_[jspace2, jspace3]
J = np.c_[jspace1, J]

print(np.array_repr(J))
# print(np.array_repr(jspace2))
# print(np.array_repr(jspace3))

Jans = np.array([[0, 0.982004235117, 0.982004235117], 
                 [0, 0.188858894977, 0.188858894977], 
                 [1, 0, 0], [2, 0, -0.164858421865], 
                 [0, 0, 0.857209656374], 
                 [0, -1.96400847023, 1.93958132709]])
print(np.array_repr(Jans))

array([[ 0.        , -1.        ,  1.        ],
       [ 1.        ,  0.        ,  0.        ],
       [ 0.        ,  0.        ,  0.        ],
       [ 0.        ,  0.        ,  0.        ],
       [ 0.        , -3.92801694,  0.        ],
       [ 2.        , -0.75543558,  2.        ]])


In [86]:
# q2

theta = np.array([[0.60000000], [0.90000000], [0.32000000], [-0.41000000], [-0.21000000], [-0.19000000]])
endeffector_twist = np.array([[-0.81213152], [0.10905207], [-0.55961026], [-0.12993913], [3.72950583], [-2.38478328]])
jacobian = np.array([[0.25785003, -0.00000000, 0.00000000, 0.00000000, 1.00000000, 0.00000000], [-0.20141082, 0.97803091, 0.00000000, -0.97803091, -0.00000000,  0.00000000], [0.94495875, 0.20845990, 0.00000000, -0.20845990, -0.00000000,  0.00000000], [-2.07074458, 5.12379157, -0.39860933, -1.16182961, -0.00000000,  -0.00000000], [-4.99061938, -0.35896634, -0.19118291, -0.00000000, -2.00000000,  1.00000000], [-0.49867063, 1.68416170, 0.89697252, -0.00000000, 3.81000000,  0.00000000]])
T_1in0 = np.array([[0.54554906, 0.83755407, 0.02965485, -3.04583102], [0.25785003, -0.20141082, 0.94495875, 4.50651454], [0.79742685, -0.50787486, -0.32584283, -5.32439431], [0.00000000, 0.00000000, 0.00000000, 1.00000000]])

Jp = jacobian.T @ np.linalg.inv((jacobian @ jacobian.T))

print(np.array_repr(Jp@endeffector_twist))


array([[-0.59      ],
       [-0.3       ],
       [ 0.38000001],
       [-0.28999999],
       [-0.66      ],
       [-0.56999999]])


In [7]:
# q3

theta = np.array([[-0.65000000], [0.91000000], [0.83000000], [0.81000000], [0.11000000], [0.07000000], [0.27000000], [0.57000000]])
jacobian = np.array([[-0.73593251, -0.07569197, 0.00000000, -0.99395610, 0.00000000,  0.00000000, 0.00000000, 1.00000000], [-0.64147485, -0.23995141, 0.00000000, -0.05923989, 0.84190098,  0.00000000, 0.00000000, 0.00000000], [-0.21659493, 0.96782955, 0.00000000, -0.09242246, -0.53963205,  0.00000000, 0.00000000, -0.00000000], [-0.39921557, -3.85333787, -0.07569197, -0.00000000, 0.27000000,  1.00000000, 0.00000000, 0.00000000], [-0.10890897, 3.71472783, -0.23995141, -0.51990984, -4.35483063,  0.00000000, 0.53963205, -0.00000000], [1.67897781, 0.61962096, 0.96782955, 0.33324585, -6.79414087,  -0.00000000, 0.84190098, 0.00000000]])
T_1in0 = np.array([[-0.73593251, -0.64147485, -0.21659493, -1.37864159], [-0.48980585, 0.72528317, -0.48379185, -1.58308685], [0.46743296, -0.24994869, -0.84795759, 0.69572750], [0.00000000, 0.00000000, 0.00000000, 1.00000000]])
dtheta0 = np.array([[-0.25000000], [0.43000000], [-1.35000000], [-0.40000000], [1.72000000], [1.97000000], [0.47000000], [-0.73000000]])

Jp = jacobian.T @ np.linalg.inv((jacobian @ jacobian.T))

ans = (np.eye(len(dtheta0)) - (Jp@jacobian))@dtheta0

print(np.array_repr(ans))



array([[ 0.27366583],
       [ 0.18598524],
       [ 0.47362119],
       [-0.15644401],
       [ 0.25051573],
       [ 0.7941257 ],
       [ 0.85647805],
       [ 0.05997869]])


In [103]:
# q4


theta = np.array([[0.83000000], [0.96000000], [0.55000000], [0.62000000], [0.61000000], [-0.39000000], [0.47000000], [-0.98000000], [-0.45000000]])
wrench_in_frame1 = np.array([[-0.35000000], [-7.00000000], [0.52000000], [9.20000000], [-1.17000000], [8.27000000]])
jacobian = np.array([[0.20284936, 0.00000000, 0.96882916, 0.00000000, -0.24726267, 0.80281008,  0.43496553, 0.00000000, 0.00000000], [0.95858526, 0.00000000, -0.22612069, 0.00000000, -0.90772497,  -0.38780148, 0.90044710, 0.00000000, -0.00000000], [-0.19991606, 0.00000000, -0.10119038, 0.00000000, -0.33896393,  0.45288629, -0.00000000, 0.00000000, -1.00000000], [0.05723960, -0.20284936, -0.39298999, 0.96882916, 2.25312289,  -1.95442032, -1.80089420, 0.90044710, 2.00000000], [0.16321768, -0.95858526, -1.85435958, -0.22612069, -0.00955820,  1.99393572, 0.86993107, -0.43496553, 0.00000000], [0.84069825, 0.19991606, 0.38115193, -0.10119038, -1.61798032,  5.17189332, 1.84993107, -0.00000000, 0.00000000]])
T_1in0 = np.array([[-0.61895888, 0.28372176, 0.73238779, 0.58657195], [0.75877667, -0.02482458, 0.65087764, -0.62659658], [0.20284936, 0.95858526, -0.19991606, -0.96552175], [0.00000000, 0.00000000, 0.00000000, 1.00000000]])

tor = (jacobian).T@wrench_in_frame1

# for space
# rk.getAdjoint(np.linalg.inv(T_1in0))@  

print(np.array_repr(tor))

array([[ 0.40316371],
       [ 0.90863646],
       [ 2.89735489],
       [ 8.34094504],
       [13.62357192],
       [25.12711372],
       [-8.74248368],
       [ 8.79302299],
       [17.88      ]])


In [5]:
# q5

T_F1_in_S = np.array([[-0.07078124, 0.09530216, 0.99292876, 2.18295144], [0.86142085, 0.50773369, 0.01267394, 0.63191679], [-0.50293553, 0.85622661, -0.11803328, 0.60874122], [0.00000000, 0.00000000, 0.00000000, 1.00000000]])
T_F2_in_S = np.array([[0.02423929, -0.86294672, -0.50471320, 2.23575819], [0.99664033, 0.06036799, -0.05535125, 0.64832019], [0.07823371, -0.50167585, 0.86151078, 0.62562113], [0.00000000, 0.00000000, 0.00000000, 1.00000000]])
p_com_in_S = np.array([[2.21361335], [0.63974279], [0.60293296]])
W1_in_F1 = np.array([[-0.27916912], [-0.47757174], [0.50552663], [0.20819284], [0.12271182], [0.00306311]])
W2_in_F2 = np.array([[0.48927889], [0.26712968], [0.49153016], [0.35378576], [0.02142933], [-0.01964850]])
gravity_constant = 9.81000000

f1 = rk.getAdjoint(np.linalg.inv(T_F1_in_S)).T@W1_in_F1
f2 = rk.getAdjoint(np.linalg.inv(T_F2_in_S)).T@W2_in_F2

print(np.array_repr(f1))
print(np.array_repr(f2))
print(np.array_repr(f1+f2))




array([[ 3.29074384e-01],
       [-4.76554343e-01],
       [ 1.99412952e-01],
       [ 3.90992263e-09],
       [ 2.41685398e-01],
       [ 9.49883227e-10]])
array([[-6.88822638e-01],
       [ 4.76554344e-01],
       [ 1.12136992e+00],
       [ 2.36538256e-09],
       [ 3.54978370e-01],
       [-2.65271265e-09]])
array([[-3.59748254e-01],
       [ 1.06784548e-09],
       [ 1.32078287e+00],
       [ 6.27530520e-09],
       [ 5.96663768e-01],
       [-1.70282942e-09]])
