In [2]:
import numpy as np
import math as math
import matplotlib.pylab as plt
from mpl_toolkits.mplot3d import Axes3D
from numpy import sin,cos,pi,exp,sqrt
from mpl_toolkits.mplot3d.art3d import Poly3DCollection, Line3DCollection

from ipywidgets import interact, interactive, fixed, interact_manual, FloatSlider
import ipywidgets as widgets
from IPython.display import display, Latex, Markdown

#this is the library that contains all the rigid body tranforms functions
import transforms as tm
import robot_kinematics as rk
import allfunc as fn

In [27]:
#Q1

R = np.array([[0,0,1],
              [0,1,0],
              [-1,0,0]])

P = np.array([[0,-4,4]])

T_0a = tm.hom(R,P)

T_a1 = tm.hom(tm.Rx(0), [0, 0, 0])

T_01 = T_0a@T_a1

print(np.array_repr(T_01))

array([[ 0.,  0.,  1.,  0.],
       [ 0.,  1.,  0., -4.],
       [-1.,  0.,  0.,  4.],
       [ 0.,  0.,  0.,  1.]])


In [54]:
#Q2
# remove inside brackets for p

p = np.array([-1.03979456, -0.04689069, 0.74147755])
R = np.array([[-0.26644878, -0.03594336, 0.96317866], [0.33220423, -0.94149779, 0.05676498], [0.90479025, 0.33509698, 0.26280147]])
v1_in1 = np.array([[0], [0], [0],[-0.00849640], [0.33192355], [0.96272184]])
v1_in0 = np.array([[0.91760654], [-0.26067894], [0.35654383]])
v2_in1 = np.array([[0], [0], [0],[-0.24817273], [0.04314398], [-0.16878532]])

#[0], [0], [0],

T = tm.hom((R),p)

v = rk.getAdjoint(T)@v2_in1
print(np.array_repr(v))



array([[ 0.        ],
       [ 0.        ],
       [ 0.        ],
       [-0.09799584],
       [-0.13264509],
       [-0.25444388]])


In [69]:
#Q3
import scipy.linalg


R_1in0 = np.array([[0.40669110, -0.81446060, 0.41383123], [0.86284801, 0.19361215, -0.46691290], [0.30015940, 0.54696277, 0.78149604]])
R_2in0 = np.array([[-0.05032098, 0.58363870, -0.81045276], [-0.93451032, 0.25878133, 0.24438225], [0.35236098, 0.76967402, 0.53239426]])


R_12 = np.linalg.inv(R_1in0)@R_2in0

R_21 = np.linalg.inv(np.linalg.inv(R_1in0)@R_2in0)

omegaskew = scipy.linalg.logm(R_21)

omega = np.array([[omegaskew[2][1]],[-omegaskew[2][0]],[omegaskew[1][0]]])

theta = ((omega**2).sum()**0.5)

omega_hat = omega / theta

omega_hat_0 = (R_12)@omega_hat

print(np.array_repr(omegaskew))
print(np.array_repr(omega))


print(np.array_repr(omega_hat_0), theta)




array([[-4.70602310e-09, -1.77477373e+00,  1.80511101e+00],
       [ 1.77477369e+00,  7.94676993e-09, -7.67807687e-01],
       [-1.80511098e+00,  7.67807673e-01, -3.34378510e-09]])
array([[0.76780767],
       [1.80511098],
       [1.77477369]])
array([[0.29025014],
       [0.68237624],
       [0.670908  ]]) 2.645330965222674


In [77]:
#Q4
import scipy.linalg

import numpy as np

T_1in0 = np.array([[0.89470477, -0.43957369, -0.07923607, 0.46201386], [0.44066292, 0.89766323, -0.00411333, 0.80972835], [0.07293541, -0.03123618, 0.99684739, 1.01210286], [0.00000000, 0.00000000, 0.00000000, 1.00000000]])
T_2in0 = np.array([[0.85301193, -0.30855956, -0.42090575, -0.03721072], [0.26930032, 0.95107315, -0.15145034, 1.02563241], [0.44704361, 0.01583889, 0.89437193, 0.73449696], [0.00000000, 0.00000000, 0.00000000, 1.00000000]])

T_12 = (np.linalg.inv(T_1in0)@T_2in0)


Vskew = scipy.linalg.logm(T_12)

V = np.array([[Vskew[2][1]],[-Vskew[2][0]],[Vskew[1][0]], [Vskew[0][3]], [Vskew[1][3]], [Vskew[2][3]]])

Vspace = rk.getAdjoint(T_1in0)@V

print(np.array_repr(Vspace))




array([[ 0.18972959],
       [-0.34482625],
       [-0.13680523],
       [-0.31846769],
       [ 0.41130046],
       [-0.51943057]])


In [86]:
# q5 body

T = np.zeros([4,4])
T[3,3] = 1

# x y and z pos
T[0,3] = -2
T[1,3] = 0
T[2,3] = 0

# new x in s frame
T[0,0] = 0
T[1,0] = 0
T[2,0] = -1
# new y in s frame
T[0,1] = 0
T[1,1] = -1
T[2,1] = 0
# new z in s frame
T[0,2] = -1
T[1,2] = 0
T[2,2] = 0

theta = np.array([[0.61000000], [0.62000000], [0.48000000], [-0.75000000]])


t0a = tm.hom(tm.Rx(-theta[0]), [-2., 0., 0.])


tab = tm.hom(tm.Ry(-theta[1]), [0., -4., 0.])


tbc = rk.translate([0., -2.-theta[2], 0.])


tcd = rk.translate([0., -2., theta[3]])



j1 = np.array([[-1.], [0.], [0.], [0.], [0.], [0.]])

j2 = np.array([[0.], [-1.], [0.], [0.], [0.], [0.]])

j3 = np.array([[0.], [0.], [0.], [0.], [-1.], [0.]])

j4 = np.array([[0.], [0.], [0.], [0.], [0.], [1.]])


jspace1 = rk.getAdjoint(np.linalg.inv(tab@tbc@tcd@T))@j1

jspace2 = rk.getAdjoint(np.linalg.inv(tbc@tcd@T))@j2

jspace3 = rk.getAdjoint(np.linalg.inv(tcd@T))@j3

jspace4 = rk.getAdjoint(np.linalg.inv(T))@j4


J = np.c_[jspace3, jspace4]
J = np.c_[jspace2, J]
J = np.c_[jspace1, J]

print(np.array_repr(J))



F = np.array([[-1.14987387], [0.92090501], [0.25940902], [-1.35279026], [0.66365274], [-1.86504900]])

print(np.array_repr(-J.T@F))



array([[-0.58103516,  0.        ,  0.        ,  0.        ],
       [ 0.        ,  1.        ,  0.        ,  0.        ],
       [ 0.81387846,  0.        ,  0.        ,  0.        ],
       [-6.90168931,  2.        ,  0.        , -1.        ],
       [ 1.77247916,  0.        ,  1.        ,  0.        ],
       [-4.92717816, -0.75      ,  0.        ,  0.        ]])
array([[-20.581522  ],
       [  0.38588876],
       [ -0.66365274],
       [ -1.35279026]])


In [90]:
# q5 space

T = np.zeros([4,4])
T[3,3] = 1

# x y and z pos
T[0,3] = -2
T[1,3] = 0
T[2,3] = 0

# new x in s frame
T[0,0] = 0
T[1,0] = 0
T[2,0] = -1
# new y in s frame
T[0,1] = 0
T[1,1] = -1
T[2,1] = 0
# new z in s frame
T[0,2] = -1
T[1,2] = 0
T[2,2] = 0

theta = np.array([[-0.96000000], [-0.31000000], [0.48000000], [0.85000000]])

t0a = tm.hom(tm.Rz(theta[0]), [0., 0., 2.])


tab = tm.hom(tm.Rz(theta[1]), [2., 0., 0.])


tbc = tm.hom(tm.Ry(-theta[2]), [0., 0., 2.])


tcd = rk.translate([-2.-theta[3], 0., 0.])



j1 = np.array([[0.], [0.], [1.], [0.], [0.], [0.]])

j2 = np.array([[0.], [0.], [1.], [0.], [0.], [0.]])

j3 = np.array([[0.], [-1.], [0.], [0.], [0.], [0.]])

j4 = np.array([[0.], [0.], [0.], [-1.], [0.], [0.]])


jspace1 = rk.getAdjoint(t0a)@j1

jspace2 = rk.getAdjoint(t0a@tab)@j2

jspace3 = rk.getAdjoint(t0a@tab@tbc)@j3

jspace4 = rk.getAdjoint(t0a@tab@tbc@tcd)@j4


J = np.c_[jspace3, jspace4]
J = np.c_[jspace2, J]
J = np.c_[jspace1, J] #q6.1

#print(np.array_repr(J))


jbody1 = rk.getAdjoint(np.linalg.inv(tab@tbc@tcd@T))@j1

jbody2 = rk.getAdjoint(np.linalg.inv(tbc@tcd@T))@j2

jbody3 = rk.getAdjoint(np.linalg.inv(tcd@T))@j3

jbody4 = rk.getAdjoint(np.linalg.inv(T))@j4


Jbody = np.c_[jbody3, jbody4]
Jbody = np.c_[jbody2, Jbody]
Jbody = np.c_[jbody1, Jbody] #q6.2

#print(np.array_repr(Jbody))

dtheta = np.array([[-0.61900473], [-0.31626343], [-0.52708959], [-0.32611121]])


V = J@dtheta  #q6.3

print(np.array_repr(V))

t01 = t0a@tab@tbc@tcd@T 

Vbody = rk.getAdjoint(np.linalg.inv(t01))@V  #q6.4

print(np.array_repr(Vbody))



F = np.array([[-1.14987387], [0.92090501], [0.25940902], [-1.35279026], [0.66365274], [-1.86504900]])

#print(np.array_repr(-J.T@F))




array([[ 0.50342372],
       [ 0.15616656],
       [-0.93526816],
       [-0.02080368],
       [ 2.10019016],
       [ 1.15452159]])
array([[ 0.82957811],
       [-0.52708959],
       [ 0.43188736],
       [-2.38198646],
       [-2.84445586],
       [-0.66109857]])


In [92]:


J = np.array([[0.00000000, 0.00000000, 0.57286746, -0.81948409, 0.55212532, 0.00000000,  0.00000000, -0.38166013], [1.00000000, 0.00000000, 0.00000000, 0.01999867, 0.29546110, 0.00000000,  0.00000000, -0.74181679], [0.00000000, 0.00000000, 0.81964802, 0.57275289, 0.77965401, 0.00000000,  0.00000000, 0.55140130], [0.00000000, 0.00000000, -0.27868033, -0.21764915, 0.72809740,  -0.38166013, 0.55212532, 2.66391403], [0.00000000, -1.00000000, 5.27859207, 2.29101156, 6.89958253,  -0.74181679, 0.29546110, 4.62213212], [-4.00000000, 0.00000000, 0.19477494, -0.39140299, -3.13031070,  0.55140130, 0.77965401, 8.06215912]])
v1 = np.array([[-0.11797294], [-0.30236721], [0.21294758], [0.25133328], [0.54528757], [0.37577990], [-0.67156146], [-0.13635068]])
v2 = np.array([[0.02685941], [0.03406339], [-0.17678547], [-0.06109388], [0.16095370], [0.41391422], [-0.51550016], [0.09866745]])
A = np.array([[-0.07417500, 1.53303027, -0.14350421, -0.01543803, 0.02257859,  0.13745531], [1.18103169, -1.25087741, 5.88492261, 1.20622592, -0.96962982,  -0.30707471], [0.45711392, 0.73529398, 0.51933653, -0.41800460, 0.01410238, 0.18628777], [-0.77734351, -0.23752101, 0.60467694, -0.08425736, -0.01397666,  -0.06201495], [0.13734353, -0.85994288, 0.32591278, 0.40389639, -0.02014361,  -0.21858020], [0.20640648, 0.47137106, 0.66966268, -0.13572015, -0.08959794,  0.10160878], [0.20547395, -0.04606019, 0.76202058, 0.27574276, -0.14008794,  -0.03784378], [-0.06624433, 0.36963371, -0.04733908, 0.13778686, 0.02203701,  0.09656447]])
B = np.array([[-0.94178568, 1.81100756, 0.71164750, 0.87828325, -0.39630012,  0.21694541], [1.58767269, -2.24459400, 6.49058993, 1.09012684, -1.13701654,  0.15678787], [1.06418097, 0.42388240, 0.88698672, -0.46002636, 0.37790251, 0.17243543], [-0.67191826, -0.95292667, 0.81918942, 0.06541284, 0.30650758,  -1.00238916], [-0.05162274, -1.67855855, 0.21070470, -0.18397650, -0.70009520,  -0.25813864], [-0.05013216, -0.30303212, 0.76462670, -0.09588607, -0.04771968,  0.62522986], [0.50068237, 0.73348801, 1.44333096, 0.58968268, 0.18213244, -0.14507230], [0.89698046, -0.40729035, -0.84509123, -0.18486871, -0.40224312,  0.34561265]])

Jplus = (J.T)@np.linalg.inv(J@J.T)

print(np.array_repr(Jplus))




array([[-0.07417499,  1.53303027, -0.14350422, -0.01543803,  0.02257859,
         0.13745531],
       [ 1.18103168, -1.2508774 ,  5.88492258,  1.2062259 , -0.96962981,
        -0.3070747 ],
       [ 0.45711392,  0.73529398,  0.51933652, -0.41800461,  0.01410238,
         0.18628777],
       [-0.77734352, -0.23752102,  0.60467695, -0.08425736, -0.01397666,
        -0.06201496],
       [ 0.13734353, -0.85994288,  0.32591279,  0.40389639, -0.02014361,
        -0.2185802 ],
       [ 0.20640649,  0.47137104,  0.66966273, -0.13572013, -0.08959795,
         0.10160878],
       [ 0.20547395, -0.04606019,  0.7620206 ,  0.27574277, -0.14008795,
        -0.03784378],
       [-0.06624433,  0.36963371, -0.04733909,  0.13778686,  0.02203701,
         0.09656447]])


In [93]:
import numpy as np

m = 65.02107484
g = 9.81000000
p_com = np.array([[-1.33496397], [0.96084429], [0.04771219]])
F_foot = np.array([[-0.69160911], [-0.06572448], [-0.49784646], [-581.50348226], [-44.97667606], [301.08526543]])
T_foot_in_0 = np.array([[-0.24756029, 0.91505074, -0.31842745, -1.09793144], [-0.85559161, -0.05225738, 0.51500696, -0.52093483], [0.45461732, 0.39993913, 0.79584659, 0.00616757], [0.00000000, 0.00000000, 0.00000000, 1.00000000]])
T_hand_in_0 = np.array([[-0.59977129, -0.42943858, -0.67517175, -1.95526759], [-0.56022557, -0.37710961, 0.73751994, 1.51979919], [-0.57133327, 0.82059177, -0.01440296, 0.02152459], [0.00000000, 0.00000000, 0.00000000, 1.00000000]])

tfh = np.linalg.inv(T_foot_in_0)@T_hand_in_0

print(np.array_repr(rk.getAdjoint(np.linalg.inv(tfh)).T@F_foot))




array([[-733.57438668],
       [ 194.96734052],
       [-709.50678935],
       [-391.73964599],
       [ 237.66307077],
       [ 469.97643948]])
